name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: export-grade
        if: always()
        run: |
          curl -X POST "https://it.bzz.ch/fgitapi/gh_grade/${{ github.repository }}/2/2"