name: Report to Moodle Workflow incl Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-lint:
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Lint the Code which is committed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  report-to-moodle:
    needs: run-lint
    if: ${{ !contains(github.actor, 'classroom') }}
    name: Report to Moodle that Linter was successfully
    runs-on: ubuntu-latest
    steps:
      - name: Call FGIT-API and send 1 point to Moodle
        if: always()
        run: |
          curl -X POST "https://it.bzz.ch/fgitapi/gh_grade/${{ github.repository }}/2/2"